export enum AppraisalEventAction {
  SUBMITTED = 'SUBMITTED',
  MANAGER_ACCEPTED = 'MANAGER_ACCEPTED',
  MANAGER_REJECTED = 'MANAGER_REJECTED',
  CEO_ACCEPTED = 'CEO_ACCEPTED',
  CEO_REJECTED = 'CEO_REJECTED',
  CEO_SENT_BACK = 'CEO_SENT_BACK',
}
