export enum AppraisalStatus {
  PENDING_MANAGER = 'PENDING_MANAGER',
  MANAGER_REJECTED = 'MANAGER_REJECTED',
  PENDING_CEO = 'PENDING_CEO',
  CEO_ACCEPTED = 'CEO_ACCEPTED',
  CEO_REJECTED = 'CEO_REJECTED',
}
