export enum LetterStatus {
  DRAFT = 'DRAFT',
  PENDING_CEO = 'PENDING_CEO',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  CEO_SIGNED = 'CEO_SIGNED',
  SENT_TO_EMPLOYEE = 'SENT_TO_EMPLOYEE',
  SIGNED = 'SIGNED',
  ARCHIVED = 'ARCHIVED',
  CANCELLED = 'CANCELLED',
}
