export enum LetterEventAction {
  SUBMITTED = 'SUBMITTED',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  CEO_SIGNED = 'CEO_SIGNED',
  SENT_TO_EMPLOYEE = 'SENT_TO_EMPLOYEE',
  EMPLOYEE_SIGNED = 'EMPLOYEE_SIGNED',
  CANCELLED = 'CANCELLED',
}
